#ifndef CONTROL_CONFIG_H
#define CONTROL_CONFIG_H

#define SELECT_INPUT_RADIO  GPIO_PIN_SET
#define SELECT_INPUT_MP3    GPIO_PIN_RESET

#define SELECT_OUTPUT_EAR   GPIO_PIN_SET
#define SELECT_OUTPUT_SPK   GPIO_PIN_RESET

#define INPUT_SELECT_GPIO_PIN   GPIO_PIN_0
#define INPUT_SELECT_GPIO_PORT  GPIOA
#define __INPUT_SELECT_GPIO()   __HAL_RCC_GPIOA_CLK_ENABLE();

#define OUTPUT_SELECT_GPIO_PIN  GPIO_PIN_0
#define OUTPUT_SELECT_GPIO_PORT GPIOA
#define __OUTPUT_SELECT_GPIO()  __HAL_RCC_GPIOA_CLK_ENABLE();

#define CONS_GPIO_PIN        GPIO_PIN_0
#define CONS_GPIO_PORT       GPIOA
#define __CONS_ENABLE_GPIO() __HAL_RCC_GPIOA_CLK_ENABLE();

#endif
