<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Real Time Audio Processor</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body onload="periodicUpdateRTC()">
    <div class="tab">
        <td>
            <a href="/index.cgi" style="padding: 14px 16px; color: black;">
                <img src="imgs/RTAP.png" alt="Logo" style="height: 65px;">
            </a>
        </td>
        <td>
            <a href="/radio.cgi" style="padding: 14px 16px;color: black;">Radio</a>
        </td>
        <td>
            <a href="/mp3.cgi" style="padding: 14px 16px;color: black;">MP3</a>
        </td>
        <td>
            <a href="/filtros.cgi" style="padding: 14px 16px;color: black;">Filtros</a>
        </td>
        <td>
